rrfs:
  - 'module help > /dev/null 2>&1 || source $(bash -l -c "echo $MODULESHOME")/init/profile'
  - "module purge"
  - "module use /contrib/spack-stack/spack-stack-1.9.1/envs/ue-oneapi-2024.2.1/install/modulefiles/Core"
  - "module load stack-oneapi/2024.2.1"
  - "module load stack-intel-oneapi-mpi/2021.13"
  - "module load cmake/3.27.9"
  - "module load parallel-netcdf/1.12.3"
  - "module load parallelio/2.6.2"
  - "module load jasper/2.0.32"
  - "module load libpng/1.6.37"
  - "export CMAKE_C_COMPILER=mpiicc"
  - "export CMAKE_CXX_COMPILER=mpiicpc"
  - "export CMAKE_Fortran_COMPILER=mpiifort"
  - "export PNETCDF=$parallel_netcdf_ROOT"
  - "mpas_build_target=intel-mpi-llvm"
mpassit:
  - 'module help > /dev/null 2>&1 || source $(bash -l -c "echo $MODULESHOME")/init/profile'
  - "module purge"
  - "module use /contrib/spack-stack/spack-stack-1.9.1/envs/ue-oneapi-2024.2.1/install/modulefiles/Core"
  - "module load stack-oneapi/2024.2.1"
  - "module load stack-intel-oneapi-mpi/2021.13"
  - "module load cmake/3.30.2"
  - "module load esmf/8.8.0"
  - "export CC=mpiicx"
  - "export CXX=mpiicpx"
  - "export FC=mpiifx"
  - "export I_MPI_CC=icx"
  - "export I_MPI_CXX=icpx"
  - "export I_MPI_FC=ifx"
  - "export I_MPI_F77=ifx"
  - "export I_MPI_F90=ifx"
upp:
  - 'module help > /dev/null 2>&1 || source $(bash -l -c "echo $MODULESHOME")/init/profile'
  - "module purge"
  - "module use /contrib/spack-stack/spack-stack-1.9.2/envs/ue-oneapi-2024.2.1/install/modulefiles/Core"
  - "module load stack-oneapi/2024.2.1"
  - "module load stack-intel-oneapi-mpi/2021.13"
  - "module load cmake/3.27.9"
  - "module load jasper/2.0.32"
  - "module load zlib/1.2.13"
  - "module load libpng/1.6.37"
  - "module load hdf5/1.14.3"
  - "module load netcdf-c/4.9.2"
  - "module load netcdf-fortran/4.6.1"
  - "module load bacio/2.4.1"
  - "module load crtm/2.4.0.1"
  - "module load g2/3.5.1"
  - "module load g2tmpl/1.13.0"
  - "module load ip/5.1.0"
  - "module load w3emc/2.10.0"
  - "module load nemsio/2.5.4"
  - "module load sigio/2.3.3"
  - "module load wrf-io/1.2.0"
  - "export CC=mpiicx"
  - "export CXX=mpiicpx"
  - "export FC=mpiifx"
  - "export I_MPI_CC=icx"
  - "export I_MPI_CXX=icpx"
  - "export I_MPI_FC=ifx"
  - "export I_MPI_F77=ifx"
  - "export I_MPI_F90=ifx"
utils:
  - 'module help > /dev/null 2>&1 || source $(bash -l -c "echo $MODULESHOME")/init/profile'
  - "module purge"
  - "module use /contrib/spack-stack/spack-stack-1.9.1/envs/ue-oneapi-2024.2.1/install/modulefiles/Core"
  - "module load stack-oneapi/2024.2.1"
  - "module load stack-intel-oneapi-mpi/2021.13"
  - "module load cmake/3.27.9"
  - "module load jasper/2.0.32"
  - "module load zlib/1.2.13"
  - "module load libpng/1.6.37"
  - "module load parallelio/2.6.2"
  - "module load g2/3.5.1"
  - "module load g2tmpl/1.13.0"
  - "module load bufr/12.1.0"
  - "module load ncio/1.1.2"
  - "module load w3emc/2.10.0"
  - "module load w3nco/2.4.1"
  - "module load nco/5.2.4"
  - "module load wgrib2/3.6.0"
  - "module load prod_util/2.1.1"
  - "export CC=mpiicx"
  - "export CXX=mpiicpx"
  - "export FC=mpiifx"
  - "export I_MPI_CC=icx"
  - "export I_MPI_CXX=icpx"
  - "export I_MPI_FC=ifx"
  - "export I_MPI_F77=ifx"
  - "export I_MPI_F90=ifx"
rdas: