fix: &fix_location
  - "FIX_RRFS_LOCATION=/scratch4/BMC/rtrr/FIX_RRFS2"
base: &common # All configs inherit from this base
  - 'module help > /dev/null 2>&1 || source $(bash -l -c "echo $MODULESHOME")/init/profile'
  - "module purge"
  - "module use /contrib/spack-stack/spack-stack-1.9.3/envs/ue-oneapi-2024.2.1/install/modulefiles/Core"
  - "module load stack-oneapi/2024.2.1"
  - "module load stack-python/3.11.7"
  - "module load stack-intel-oneapi-mpi/2021.13"
  - *fix_location
wps:
  - *common
  - "module load jasper/2.0.32"
  - "module load zlib/1.2.13"
  - "module load libpng/1.6.37"
  - "module load netcdf-c/4.9.2"
  - "module load netcdf-fortran/4.6.1"
mpas:
  - *common
  - "module load cmake/3.27.9"
  - "module load parallel-netcdf/1.12.3"
  - "module load parallelio/2.6.2"
  - "export PNETCDF=$parallel_netcdf_ROOT"
  - "mpas_build_target=intel-mpi-ursa"  # only needed for original gmake-based build
upp:
  - *common
  - "module load cmake/3.27.9"
  - "module load jasper/2.0.32"
  - "module load zlib/1.2.13"
  - "module load libpng/1.6.37"
  - "module load hdf5/1.14.3"
  - "module load netcdf-c/4.9.2"
  - "module load netcdf-fortran/4.6.1"
  - "module load bacio/2.4.1"
  - "module load crtm/2.4.0.1"
  - "module load g2/3.5.1"
  - "module load g2tmpl/1.13.0"
  - "module load ip/5.1.0"
  - "module load w3emc/2.10.0"
  - "module load nemsio/2.5.4"
  - "module load sigio/2.3.3"
  - "module load wrf-io/1.2.0"
mpassit:
  - *common
  - "module load cmake/3.30.2"
  - "module load esmf/8.8.0"
rrfs_utils:
  - *common
  - "module load cmake/3.27.9"
  - "module load jasper/2.0.32"
  - "module load zlib/1.2.13"
  - "module load libpng/1.6.37"
  - "module load parallelio/2.6.2"
  - "module load g2/3.5.1"
  - "module load g2tmpl/1.13.0"
  - "module load bufr/12.1.0"
  - "module load ncio/1.1.2"
  - "module load w3emc/2.10.0"
  - "module load w3nco/2.4.1"
  - "module load nco/5.2.4"
  - "module load wgrib2/3.6.0"
  - "module load prod_util/2.1.1"
rank_run:
  - *common
  - "module load cmake/3.27.9"
rdasapp:
  - *common
  - *fix_location
  - "module load jedi-mpas-env/1.0.0"
  - "module load jedi-fv3-env/1.0.0"
  - "module load py-jinja2/3.1.4"
  - "export CC=mpiicc"
  - "export CXX=mpiicpc"
  - "export FC=mpiifort"
  - "export MPIEXEC_EXEC=/apps/slurm/default/bin/srun"
  - "export MPIEXEC_NPROC=-n"
  - "export BUILD_JOBS=12"
  - "export RDAS_DATA=/scratch4/BMC/rtrr/RDAS_DATA"
